CREATE TABLE mentores (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
username VARCHAR(45) NOT NULL UNIQUE,
data_nascimento DATE NOT NULL
);

CREATE TABLE mentorados (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
username VARCHAR(45) NOT NULL UNIQUE,
data_nascimento DATE NOT NULL
);

CREATE TABLE areas (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(200) NOT NULL
);